version: "3"
services:
  wp-db:
    image: "postgres"
    container_name: "wp_problem_solving"
    environment:
      - POSTGRES_USER=wp_problem_solving
      - POSTGRES_PASSWORD=wp_problem_solving
      - POSTGRES_DB=wp_problem_solving
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
